package dev.thilanka.resolvr.enums;

public enum AuditAction {
    CREATED, ASSIGNED, STARTED,
    ANALYSIS_ADDED, ANALYSIS_EDITED,
    SOLUTION_ADDED, SOLUTION_EDITED,
    ESCALATED_TO_ENGINEER, CUSTOMER_FEEDBACK_TAKEN,
    MARKED_RESOLVED, CLOSED, REOPENED, REASSIGNED, COMMENT_ADDED
}
